# Generated by Django 2.2 on 2020-01-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='moneyGiven',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProject', models.PositiveIntegerField()),
                ('financeur', models.CharField(max_length=255)),
                ('moneyGiven', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProject', models.PositiveIntegerField()),
                ('expert', models.CharField(max_length=255)),
                ('note', models.PositiveIntegerField()),
                ('comment', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('budget', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('createur', models.CharField(max_length=255)),
                ('budget_en_cours', models.PositiveIntegerField(default=0)),
                ('idCreateur', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
