# Generated by Django 2.2 on 2020-01-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='note',
        ),
        migrations.AddField(
            model_name='projet',
            name='financement_en_cours',
            field=models.IntegerField(default=0, max_length=255),
        ),
    ]
