# Generated by Django 2.2 on 2020-01-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200116_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='financement_en_cours',
            field=models.IntegerField(default=0),
        ),
    ]
