# Generated by Django 2.0 on 2020-01-11 22:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200111_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('[a-zA-Z]+', 'Only letters')]),
        ),
    ]
