# Generated by Django 2.0 on 2020-01-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200112_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('idProject', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('budget', models.IntegerField()),
                ('note', models.IntegerField()),
            ],
            options={
                'db_table': 'Projet',
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
