# Generated by Django 2.0 on 2020-01-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200113_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='idProject',
        ),
        migrations.AddField(
            model_name='projet',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
